### ISSUE TITLE
UnicodeDecodeError when using compressed delta file

### ISSUE THREAD

**Issue by 0xaf1f** [MariaNattestad/Assemblytics#24]
assemblytics from conda (with python 3) gives a UnicodeDecodeError when we use a compressed delta input file:

```
1. Filter delta file
Keeping fully unique alignments even if they are below the unique anchor length of 10000 bp
Use --unique-length X to set the unique anchor length requirement. Default is 10000, such that each alignment must have at least 10000 bp from the query that are not included in any other alignments.
header:
Traceback (most recent call last):
  File "<path>/conda/libexec/assemblytics/Assemblytics_uniq_anchor.py", line 355, in <module>
    main()
  File "<path>/conda/libexec/assemblytics/Assemblytics_uniq_anchor.py", line 352, in main
    args.func(args)
  File "<path>/conda/libexec/assemblytics/Assemblytics_uniq_anchor.py", line 32, in run
    header1 = f.readline()
  File "<path>/conda/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

This error actually occurred in the bioconda continuous integration testing, but since assemblytics doesn't return a non-zero exit code when failing, the build passed and nobody noticed:
https://circleci.com/gh/bioconda/bioconda-recipes/86757?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by MariaNattestad** [comment]
I did not put Assemblytics on Conda, so it is not supported and I'm closing this issue. Please follow installation instructions in the README only!

**Comment by 0xaf1f** [comment]
sorry for the short initial post-- I hit ctrl-enter instead of enter.

Anyway,  it's not a conda bug. I get the same thing running it out of the git clone:

```
$ Assemblytics/scripts/Assemblytics user_data/TvPSMK5FFq1RcNce2lzB/Escherichia_coli_MHAP_assembly.Assemblytics.unique_length_filtered_l10000.delta.gz out 10000 50 10000
Input delta file: user_data/TvPSMK5FFq1RcNce2lzB/Escherichia_coli_MHAP_assembly.Assemblytics.unique_length_filtered_l10000.delta.gz
Output prefix: out
Unique anchor length: 10000
Minimum variant size to call: 50
Maximum variant size to call: 10000
Logging progress updates in out/progress.log
script path: Assemblytics/scripts
1. Filter delta file
Keeping fully unique alignments even if they are below the unique anchor length of 10000 bp
Use --unique-length X to set the unique anchor length requirement. Default is 10000, such that each alignment must have at least 10000 bp from the query that are not included in any other alignments.
header:
Traceback (most recent call last):
  File "Assemblytics/scripts/Assemblytics_uniq_anchor.py", line 355, in <module>
    main()
  File "Assemblytics/scripts/Assemblytics_uniq_anchor.py", line 352, in main
    args.func(args)
  File "Assemblytics/scripts/Assemblytics_uniq_anchor.py", line 32, in run
    header1 = f.readline()
  File "<path>/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
$ echo $?
0
```

**Comment by 0xaf1f** [comment]
@MariaNattestad, please reopen this. The bug still occurs when following the README installation instructions.

**Comment by MariaNattestad** [comment]
Fixed in https://github.com/MariaNattestad/Assemblytics/pull/26
